=== aamerino/XML/edreams/vuelo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="unqualified" targetNamespace="http://www.edreams.com"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.edreams.com"
	xmlns:wac="http://www.iata.com/wac">

<xs:import namespace="http://www.iata.com/wac"
		schemaLocation="https://raw.githubusercontent.com/dfleta/XML_teoria/master/import/ejercicio_IATA/WAC.xsd"></xs:import>
	<xs:element name="busqueda"><!-- elemento global -->
		<xs:complexType>
			<xs:sequence>
				<xs:element name="idaVuelta" type="elementoVacio" />
				<xs:element name="origen" type="wac:WAC" />
				<xs:element name="destino" type="wac:WAC" />
				<xs:element name="fechaSalida" type="xs:date" />
				<xs:element name="fechaRegreso" type="xs:date" />
				<xs:element name="cantidad" type="tipoCantidad" />
				<xs:element name="escalasClase" type="tipoEscalasClase" />
				<xs:element name="hotel" type="elementoVacio"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<!-- complejos -->

	<xs:complexType name="tipoCantidad">
		<xs:sequence>
			<xs:element name="adultos" type="xs:int" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="ninos" type="xs:int" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="bebes" type="xs:int" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="tipoEscalasClase">
		<xs:sequence>
			<xs:element name="directo" type="elementoVacio" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="clase" type="tipoClase" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>



	<!-- simples -->


	<xs:simpleType name="tipoClase">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Turista"></xs:enumeration>
			<xs:enumeration value="Turista Superior"></xs:enumeration>
			<xs:enumeration value="Business"></xs:enumeration>
			<xs:enumeration value="Primera"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== aamerino/XML/edreams/vuelo.xml
<?xml version="1.0" encoding="UTF-8"?>

<edreams:busqueda xmlns:edreams="http://www.edreams.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.edreams.com vuelo.xsd ">
	<idaVuelta /> <!-- Element Content. Existe o no( puede ser idaVuelta, solo ida, multidestino -->
	<origen>PMI</origen><!-- String. Codigos determinados -->
	<destino>MAD</destino><!--String. Codigos determinados -->
	<fechaSalida>2005-02-13</fechaSalida>
	 <!-- Element Content. Solo 1, Solo fechas mayores que la fecha actual, 
		Entero. Entre 1 a 31
		Entero. Entre 1 a 12
		Entero. AÃ±o mayor que el actual -->
	
	<fechaRegreso>2005-02-20</fechaRegreso><!-- Element Content. Solo 1, Solo fechas mayores que la fecha 
			de salida -->
	

	<cantidad><!-- Element Content. Solo 1, Puede tener hasta 3 hijos -->
		<adultos>1</adultos><!-- Entero -->
		<bebes>100</bebes><!-- Entero -->
	</cantidad>
	<equipaje>
		<cantidad>1</cantidad>
		<tipo>Instrumento</tipo>
	</equipaje>
	<escalasClase> <!-- Element Content. Puede tener 2 atributos, 1 vacio, otro String -->
		<directo /><!-- Vacio -->
		<clase>Turista</clase><!-- String -->
	</escalasClase>
	<hotel /><!-- Opcional -->
</edreams:busqueda>
